### ISSUE TITLE
Douglas-Peucker always runs

### ISSUE THREAD

**Issue by jamescarter** [hgoebl/simplify-java#1]
Is it by design that the DP algorithm runs even if highestQuality is set to `false`? The java doc's don't mention that it will and implies it's an "either or" situation.

**Comment by hgoebl** [comment]
There is indeed a bug in the JavaDoc which I'm going to fix.
- `highestQuality = true` => do all the simplification with Douglas Peucker (not so fast, but better results)
- `highestQuality = false` => first reduce the number of points with a faster, but not so exact algorithm, then run Douglas Peucker on the remaining points.

@jamescarter thanks for your input.
