### ISSUE TITLE
Radia simplification sets the second point to null when simplifying a one point "line"

### ISSUE THREAD

**Issue by countrodrigo** [hgoebl/simplify-java#2]
If you pass an array with just one point, the code line of code linked will always add the `point`, which is set to null in the init code. This function should probably return a single point.

https://github.com/hgoebl/simplify-java/blob/d1bb73bf1e9d44187b73f787ea747becb013f40e/src/main/java/com/goebl/simplify/AbstractSimplify.java#L60

**Comment by hgoebl** [comment]
Thanks @countrodrigo this is indeed a bug. I'll fixed it.
In the meanwhile, one could call simplification only for lines with more than 2 points.
1-point lines and 2-point lines cannot be simplified anyway, obviously.
