### ISSUE TITLE
Does the code need an else on line 44? 

### ISSUE THREAD

**Issue by musselwhizzle** [hgoebl/simplify-java#3]
Sorry, just double checking here: reading through the code, doesn't like 44 here need to be in an else? 

https://github.com/hgoebl/simplify-java/blob/master/src/main/java/com/goebl/simplify/AbstractSimplify.java#L44

**Comment by musselwhizzle** [comment]
gah, i'm an idiot. closed.

**Comment by hgoebl** [comment]
No problem. A comment at this line wouldn't hurt as everybody expects an `else` here.
